# 数据库连接串 & 密码
spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/foodie-shop?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=UTC'
    username: '{cipher}20f8b0a5d9d886405655ea79c3b8e19d41bbd6490cb7855c1716e61507275ce4'
    password: '{cipher}c9c64f48989d139ff6710d81f98574b5b9a7daab154d67e8c80ac7a47e93a1bc'
  redis:
    # Redis 单机实例
    database: 0
    host: 132.232.178.235
    port: 6379
    password: '{cipher}c9c64f48989d139ff6710d81f98574b5b9a7daab154d67e8c80ac7a47e93a1bc'

# 功能开关 - 开启/关闭注册功能
userservice:
  registration:
    disable: true